import '../model/question_type_model.dart';

List<QuestionTypeModel> questionsList = [
   QuestionTypeModel(questionTxt: "", questionMark: 0, questionType: "type 0"),
  QuestionTypeModel(questionTxt: "Fill in the blanks", questionMark: 1, questionType: "type 1"),
  QuestionTypeModel(questionTxt: "Write the number names for the given numbers", questionMark: 1, questionType: "type 2"),
  QuestionTypeModel(questionTxt: "Write the number for the given number names", questionMark: 1, questionType: "type 3"),
  QuestionTypeModel(questionTxt: "Write the given numbers in expanded form", questionMark: 1, questionType: "type 4"),
  QuestionTypeModel(questionTxt: "Write the following in short form", questionMark: 1, questionType: "type 5"),
  QuestionTypeModel(questionTxt: "Write the face value and place value of the underlined digit", questionMark: 1, questionType: "type 6"),
  QuestionTypeModel(questionTxt: "Form the greatest and smallest number with the given digits", questionMark: 1, questionType: "type 7"),
  QuestionTypeModel(questionTxt: "Solve the following sums", questionMark: 1, questionType: "type 8"),
  QuestionTypeModel(questionTxt: "Story Problems(2M)", questionMark: 2, questionType: "type 9"),
  QuestionTypeModel(questionTxt: "Identify the given shapes and name them(1M)", questionMark: 1, questionType: "type 10"),
  QuestionTypeModel(questionTxt: "Tables( ½ M)", questionMark: 0.5, questionType: "type 11"),
  QuestionTypeModel(questionTxt: "State the ordinal number name for the following numbers(1M)", questionMark: 1, questionType: "type 12"),
  QuestionTypeModel(questionTxt: "Single Digit Addition(1M)", questionMark: 1, questionType: "type 13"),
  QuestionTypeModel(questionTxt: "Addition of 3 Single numbers(1M)", questionMark: 1, questionType: "type 14"),
  QuestionTypeModel(questionTxt: "Two digit addition(1M)", questionMark: 1, questionType: "type 15"),
  QuestionTypeModel(questionTxt: "Addition with carry(2M)", questionMark: 2, questionType: "type 16"),
  QuestionTypeModel(questionTxt: "Addition on number line(1M)", questionMark: 1, questionType: "type 17"),
  QuestionTypeModel(questionTxt: "How many tens and ones are there. (1M)", questionMark: 1, questionType: "type 18"),
  QuestionTypeModel(questionTxt: "Write before, after, between numbers(1M)", questionMark: 1, questionType: "type 19"),
  QuestionTypeModel(questionTxt: "Rearrange The following numerals descending order(1M)", questionMark: 1, questionType: "type 20"),
  QuestionTypeModel(questionTxt: "Rearrange The following numerals ascending order(1M)", questionMark: 1, questionType: "type 21"),
  QuestionTypeModel(questionTxt: "Match the pictures of the object with the name of their( ½ M) ", questionMark: 1, questionType: "type 22"),
  QuestionTypeModel(questionTxt: "Draw the hands on the clock(1M)", questionMark: 1, questionType: "type 23"),
  QuestionTypeModel(questionTxt: "State the time on the clock. (1M)", questionMark: 1, questionType: "type 24"),
  QuestionTypeModel(questionTxt: "What comes before, after, between? (Days or months) (1M)", questionMark: 1, questionType: "type 25"),
  QuestionTypeModel(questionTxt: "Answer the following questions(2M)", questionMark: 2, questionType: "type 26"),
  QuestionTypeModel(questionTxt: "Poem(2M)", questionMark: 2, questionType: "type 27"),
  QuestionTypeModel(questionTxt: "True and False(1M)", questionMark: 1, questionType: "type 28"),
  QuestionTypeModel(questionTxt: "Choose the correct answer(1M)", questionMark: 1, questionType: "type 29"),
  QuestionTypeModel(questionTxt: "Glossary(1M)", questionMark: 1, questionType: "type 30"),
  QuestionTypeModel(questionTxt: "Rhyming Words(1M)", questionMark: 1, questionType: "type 31"),
  QuestionTypeModel(questionTxt: "Match the following(1M)", questionMark: 1, questionType: "type 32"),
  QuestionTypeModel(questionTxt: "Missing letters(1M)", questionMark: 1, questionType: "type 33"),
  QuestionTypeModel(questionTxt: "Break the Compound words(1M)", questionMark: 1, questionType: "type 34"),
  QuestionTypeModel(questionTxt: "Complete the Sentences (1M)", questionMark: 1, questionType: "type 35"),
  QuestionTypeModel(questionTxt: "Do as Directed (1M)", questionMark: 1, questionType: "type 36"),
  QuestionTypeModel(questionTxt: "Do as Directed (2M)", questionMark: 1, questionType: "type 37"),
  QuestionTypeModel(questionTxt: "Use the following pictograph to answer the questions given below(1M)", questionMark: 1, questionType: "type 38"),
  QuestionTypeModel(questionTxt: "Give two example of each ( ½ M)", questionMark: 0.5, questionType: "type 39"),
  QuestionTypeModel(questionTxt: "Answer in one word(1M)", questionMark: 1, questionType: "type 40"),
  QuestionTypeModel(questionTxt: "Answer in short (2M)", questionMark: 2, questionType: "type 41"),
  QuestionTypeModel(questionTxt: "Answer in long(3M)", questionMark: 3, questionType: "type 42"),
  QuestionTypeModel(questionTxt: "Circle the odd one, out giving reasons(1M)", questionMark: 1, questionType: "type 43"),
  QuestionTypeModel(questionTxt: "Lable the parts (1M)", questionMark: 1, questionType: "type 44"),
  QuestionTypeModel(questionTxt: "Choose the correct word( ½ M)", questionMark: 0.5, questionType: "type 45"),
  QuestionTypeModel(questionTxt: "Give Reason(1M)", questionMark: 1, questionType: "type 46"),
  QuestionTypeModel(questionTxt: "Read the passage and answer the questions that follow. (Unseen)(2M)", questionMark: 2, questionType: "type 47"),
  QuestionTypeModel(questionTxt: "Read the poem and answer the questions that follow. (Unseen)", questionMark: 2, questionType: "type 48"),
  QuestionTypeModel(questionTxt: "Read the passage and answer the questions that follow. (Seen)(2M)", questionMark: 2, questionType: "type 49"),
  QuestionTypeModel(questionTxt: "Give Reference to the context.(1M)", questionMark: 1, questionType: "type 50"),
  QuestionTypeModel(questionTxt: "Fill in the blanks to compete the sentences taken from your lessons.(1M)", questionMark: 1, questionType: "type 51"),
  QuestionTypeModel(questionTxt: "Fill in the blanks with correct word from the option.(1M)", questionMark: 1, questionType: "type 52"),
  QuestionTypeModel(questionTxt: "Write the words in alphabetical order.(1M)", questionMark: 1, questionType: "type 53"),
  QuestionTypeModel(questionTxt: "Choose and the correct spelling.(1M)", questionMark: 1, questionType: "type 54"),
  QuestionTypeModel(questionTxt: "Story Problems(3M)", questionMark: 3, questionType: "type 55"),
  QuestionTypeModel(questionTxt: "Read the sentences & answer the questions(1M)", questionMark: 1, questionType: "type 56"),
  QuestionTypeModel(questionTxt: "Read the passage & answer the questions(1M)", questionMark: 1, questionType: "type 57"),
  QuestionTypeModel(questionTxt: "Define the following(1M)", questionMark: 1, questionType: "type 58"),
  QuestionTypeModel(questionTxt: "Answer in Brief(4M)", questionMark: 4, questionType: "type 59"),
  QuestionTypeModel(questionTxt: "Answer in very long (5M)", questionMark: 5, questionType: "type 60"),
  QuestionTypeModel(questionTxt: "Graph Questions(4M)", questionMark: 4, questionType: "type 61"),
  QuestionTypeModel(questionTxt: "On the basis of your understanding of the stories, choose the correct option.(1M)", questionMark: 1, questionType: "type 62"),
  QuestionTypeModel(questionTxt: "Give a character sketch.(1M)", questionMark: 1, questionType: "type 63"),
  QuestionTypeModel(questionTxt: "Give reference to the  context.(1M)", questionMark: 1, questionType: "type 64"),
  QuestionTypeModel(questionTxt: "Write the antonyms.(2M)", questionMark: 2, questionType: "type 65"),
  QuestionTypeModel(questionTxt: "Write the synonyms.(2M)", questionMark: 2, questionType: "type 66"),
  QuestionTypeModel(questionTxt: "Fill in the gap with correct word from the option.(1M)", questionMark: 1, questionType: "type 67"),
  QuestionTypeModel(questionTxt: "Fill in the gap with the exact word used in your story.(1M)", questionMark: 1, questionType: "type 68"),
  QuestionTypeModel(questionTxt: "Write an idiom in the gap which suits the sentence.(1M)", questionMark: 1, questionType: "type 69"),
  QuestionTypeModel(questionTxt: "Name the figure of speech used in the sentence.(1M)", questionMark: 1, questionType: "type 70"),
  QuestionTypeModel(questionTxt: "Complete the sentences with idioms(1M)", questionMark: 1, questionType: "type 71"),
  QuestionTypeModel(questionTxt: "Map Question(4M)", questionMark: 4, questionType: "type 72"),
  QuestionTypeModel(questionTxt: "सही उत्तर चुनकर लिखिए|(1M)", questionMark: 1, questionType: "type 73"),
  QuestionTypeModel(questionTxt: "शब्दों को उनके अर्थ के साथ जोडीए|(1M)", questionMark: 1, questionType: "type 74"),
  QuestionTypeModel(questionTxt: "निम्नलिखित शब्दों के विलोम शब्द लिखिए|(1M)", questionMark: 1, questionType: "type 75"),
  QuestionTypeModel(questionTxt: "निम्नलिखित शब्दों के बहुवचन रूप लिखिए|(1M)", questionMark: 1, questionType: "type 76"),
  QuestionTypeModel(questionTxt: "सही या गलत लिखिए|(1M)", questionMark: 1, questionType: "type 77"),
  QuestionTypeModel(questionTxt: "दिए गए वाक्यों के काल पहचानकर लिखिए|(1M)", questionMark: 1, questionType: "type 78"),
  QuestionTypeModel(questionTxt: "एक वाक्य में उत्तर लिखिए|(1M)", questionMark: 1, questionType: "type 79"),
  QuestionTypeModel(questionTxt: "दो-तीन वाक्यों में उत्तर लिखिए|(2M)", questionMark: 2, questionType: "type 80"),
  QuestionTypeModel(questionTxt: "निचे दिए गए गद्यांश को पढ़कर प्रश्नों के उत्तर लिखिए|(mcq)(5M)", questionMark: 5, questionType: "type 81"),
  QuestionTypeModel(questionTxt: "चित्र का आठ से दस वाक्यों में वर्णन कीजिए|(5M)", questionMark: 5, questionType: "type 82"),
  QuestionTypeModel(questionTxt: "दिए गए शब्दों का वाक्यों में प्रयोग कीजिए|(1M)", questionMark: 1, questionType: "type 83"),
  QuestionTypeModel(questionTxt: "पर्यायवाची शब्द लिखिए|(1M)", questionMark: 1, questionType: "type 84"),
  QuestionTypeModel(questionTxt: "वचन बदलकर लिखिए|(1M)", questionMark: 1, questionType: "type 85"),
  QuestionTypeModel(questionTxt: "निम्नलिखित संवाद किसने किससे कहा लिखिए|(1M)", questionMark: 1, questionType: "type 86"),
  QuestionTypeModel(questionTxt: "वाक्य में से कारक पहचानकर लिखिए|(1M)", questionMark: 1, questionType: "type 87"),
  QuestionTypeModel(questionTxt: "दिए गए शब्दों का वर्ण-विच्छेद कीजिए|(1M)", questionMark: 1, questionType: "type 88"),
  QuestionTypeModel(questionTxt: "गद्यांश को पढ़कर प्रश्नों के उत्तर लिखिए| (mcq)(5M)", questionMark: 5, questionType: "type 89"),
  QuestionTypeModel(questionTxt: "पद्यांश को पढ़कर प्रश्नों के उत्तर लिखिए|(mcq)(5M)", questionMark: 5, questionType: "type 90"),
  QuestionTypeModel(questionTxt: "सही उत्तर चुनकर लिखिए| (व्याकरण में से)(1M)", questionMark: 1, questionType: "type 91"),
  QuestionTypeModel(questionTxt: "विस्तार से उत्तर लिखिए|(3M)", questionMark: 3, questionType: "type 92"),
  QuestionTypeModel(questionTxt: "बालराम कथापाठ प्रश्नों के उत्तर लिखिए|(1M)", questionMark: 1, questionType: "type 93"),
  QuestionTypeModel(questionTxt: "निम्नलिखित विषय पर संवाद लेखन कीजिए|(5M)", questionMark: 5, questionType: "type 94"),
];